package cb.psi

import cb.CbLanguage
import com.intellij.psi.tree.IElementType

class CbToken(debugName: String) : IElementType(debugName, CbLanguage) {
  companion object {
    @JvmField val WHITESPACE = CbToken("whitespace")
    @JvmField val NEWLINE = CbToken("newline")
    @JvmField val COMMENT = CbToken("comment")
    @JvmField val NUMBER = CbToken("number")

    @JvmField val GREATER_GREATER_EQ = CbToken("GREATER_GREATER_EQ")
    @JvmField val LESS_LESS_EQ = CbToken("LESS_LESS_EQ")
    @JvmField val AMP_EQ = CbToken("AMP_EQ")
    @JvmField val CARET_EQ = CbToken("CARET_EQ")
    @JvmField val COLON_EQ = CbToken("COLON_EQ")
    @JvmField val COLON_EXCL = CbToken("COLON_EXCL")
    @JvmField val EQ_EQ = CbToken("EQ_EQ")
    @JvmField val EQ_GREATER = CbToken("EQ_GREATER")
    @JvmField val EXCL_EQ = CbToken("EXCL_EQ")
    @JvmField val GREATER_EQ = CbToken("GREATER_EQ")
    @JvmField val GREATER_GREATER = CbToken("GREATER_GREATER")
    @JvmField val LESS_EQ = CbToken("LESS_EQ")
    @JvmField val LESS_GREATER = CbToken("LESS_GREATER")
    @JvmField val LESS_LESS = CbToken("LESS_LESS")
    @JvmField val LESS_MINUS = CbToken("LESS_MINUS")
    @JvmField val MINUS_EQ = CbToken("MINUS_EQ")
    @JvmField val MINUS_GREATER = CbToken("MINUS_GREATER")
    @JvmField val MINUS_MINUS = CbToken("MINUS_MINUS")
    @JvmField val PERCENT_EQ = CbToken("PERCENT_EQ")
    @JvmField val PIPE_EQ = CbToken("PIPE_EQ")
    @JvmField val PLUS_EQ = CbToken("PLUS_EQ")
    @JvmField val PLUS_PLUS = CbToken("PLUS_PLUS")
    @JvmField val SLASH_EQ = CbToken("SLASH_EQ")
    @JvmField val STAR_EQ = CbToken("STAR_EQ")
    @JvmField val TILDE_EQ = CbToken("TILDE_EQ")
    @JvmField val AMP = CbToken("AMP")
    @JvmField val CARET = CbToken("CARET")
    @JvmField val COLON = CbToken("COLON")
    @JvmField val EQ = CbToken("EQ")
    @JvmField val EXCL = CbToken("EXCL")
    @JvmField val GREATER = CbToken("GREATER")
    @JvmField val LESS = CbToken("LESS")
    @JvmField val MINUS = CbToken("MINUS")
    @JvmField val PERCENT = CbToken("PERCENT")
    @JvmField val PERIOD = CbToken("PERIOD")
    @JvmField val PIPE = CbToken("PIPE")
    @JvmField val PLUS = CbToken("PLUS")
    @JvmField val QUESTION = CbToken("QUESTION")
    @JvmField val SLASH = CbToken("SLASH")
    @JvmField val STAR = CbToken("STAR")
    @JvmField val TILDE = CbToken("TILDE")
    @JvmField val COMMA = CbToken("COMMA")
    @JvmField val SEMI = CbToken("SEMI")
    @JvmField val OPEN_BRACKET = CbToken("OPEN_BRACKET")
    @JvmField val CLOSE_BRACKET = CbToken("CLOSE_BRACKET")
    @JvmField val OPEN_PAREN = CbToken("OPEN_PAREN")
    @JvmField val CLOSE_PAREN = CbToken("CLOSE_PAREN")
    @JvmField val OPEN_BRACE = CbToken("OPEN_BRACE")
    @JvmField val CLOSE_BRACE = CbToken("CLOSE_BRACE")
  }
}